
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


export const GET_ALL_GRADES = "GET_ALL_GRADES";
export const GET_COURSES_BY_GRADE = "GET_COURSES_BY_GRADE";
export const GET_COURSE = "GET_COURSE";
export const GET_CHAPTERS_BY_COURSE = "GET_CHAPTERS_BY_COURSE";
export const GET_ARTICLES_BY_CHAPTER = "GET_ARTICLES_BY_CHAPTER";

